shared:
    image: node:8
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - meta: meta set meta.firstA $(echo date +"%s")
    publish:
        requires: [~pr, ~commit]
        steps:
            - meta: meta set meta.firstB $(echo date +"%s")
    promote:
        requires: [publish]
        steps:
            - meta: |
                meta get meta
                cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
