shared:
    image: node:8
jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - validate: sd-cmd validate -f sd-command.yaml
    publish:
        requires: [main]
        steps:
            #- publish: sd-cmd publish -f sd-command.yaml
            - publish: sd-cmd publish -f sd-command.yaml -t latest
    promote:
        requires: [publish]
        steps:
            #- publish: sd-cmd promote tiff/command 1.0.1 -t stable
            - promote: sd-cmd promote tiff/command 1.0.2 stable
    external_fork:
        requires: [~sd@1:main]
        # requires: [~sd@3851:main]
        steps:
            - echo: echo hi
            - sleep: sleep 30m
