shared:
    image: node:8
    steps:
        - echo: echo hi
jobs:
    main:
        requires: []
    fork1:
        requires: [main]
    fork2:
        requires: [main]
    fork3:
        requires: [main]
    fork4:
        requires: [main]
    join:
        requires: [fork1, fork2, fork3, fork4]
