shared:
    image: node:8
    steps:
        - echo: echo hi
jobs:
  pre-main:
    requires: [~commit, ~pr, ~sd@6:other-job]
    steps:
      - noop: echo "noop"
  main:
    requires: [pre-main]
  start-1:
    requires: [pre-main, main]
  start-2:
    requires: [pre-main, main]
  start-3:
    requires: [pre-main, main]
  start-4:
    requires: [pre-main, main]
  start-5:
    requires: [pre-main, main]
  start-6:
    requires: [pre-main, main]
  start-7:
    requires: [pre-main, main]
  final:
    requires: [start-1, start-2, start-3, start-4, start-5, start-6, start-7]
    steps:
        - echo: sleep 30
